### ISSUE TITLE
Block rotations randomly shuffle

### ISSUE THREAD

**Issue by sophuric** [rfresh2/NoTextureRotations#4]
Seems to happen randomly, waiting randomly causes it to happen

Possible solution would be to have the block rotations depending on the current block position relative to the chunk or something so that they're fixed but still safe

**Comment by rfresh2** [comment]
which mode do you have enabled? "No Rotations" or "Secure Random"?

**Comment by sophuric** [comment]
Secure Random, this doesn't happen with No Rotations, only Secure Random because it generates a different value for the same blocks each time

**Comment by rfresh2** [comment]
yeah this is the intended behavior then. 

A consistent function could be reversed. Even knowing just relative position in the chunk is information that could possibly be useful for attackers.

I'm open to suggestions but i can't think of any good solutions

**Comment by sophuric** [comment]
perhaps a hash with the relative chunk coordinate and a random hash that is unique to each game instance? (i.e randomly generated upon the game starting or joining a server/world)

**Comment by rfresh2** [comment]
i added a new "random offset" mode https://github.com/rfresh2/NoTextureRotations/commit/18855a38d1eac032df65c4d70df430742e0795bd

a new random offset is generated on every game launch.

however, if you were to reveal the coordinates of block rotations/offsets during the game session it is possible to reverse the offset.  i've added a note to the setting description regarding this.

but anyway this should get you the behavior you were wanting

**Comment by sophuric** [comment]
Looks good, I suppose I can close this issue now
