### ISSUE TITLE
Collision hitboxes are also updated

### ISSUE THREAD

**Issue by sophuric** [rfresh2/NoTextureRotations#5]
Steps to reproduce
1. Join a server
2. Find a block whose which has a collision dependant on block rotational randomness such as pointed dripstone
3. Walk into the block
4. Get lagged back by the server for being inside of a block that the player shouldn't be

This might be difficult to fix as you'd need to mixin to rendering stuff, rather than block behaviour

**Comment by rfresh2** [comment]
you can set offsets to be enabled in the settings

but i don't think this will be fixable while having offsets disabled

mixins into rendering stuff is not something i want to do as it will be much more difficult to maintain mod compatibility (e.g. mods like sodium completely rewriting the rendering pipeline)
