### ISSUE TITLE
Secure Random causes constant shuffling on PVP Legacy

### ISSUE THREAD

**Issue by Kladki** [rfresh2/NoTextureRotations#6]
At one location in the lobby of play.pvplegacy.net, the blocks shuffle multiple times per second, which is very annoying.

Steps to reproduce:
1. Connect to play.pvplegacy.net
2. Right click the compass
3. Click on the iron sword
4. Turn 180 degrees
5. See issue

https://github.com/user-attachments/assets/1629686b-8a8f-4622-9eaf-664dad2797f4

**Comment by rfresh2** [comment]
Use Random Offset mode if you want rotations enabled but you want stable visuals. 

Secure random cannot retain stable visuals just by the nature of it being truly random

**Comment by Kladki** [comment]
> Secure random cannot retain stable visuals just by the nature of it being truly random

I am curious why all the other blocks in the map have stable visuals, while this area does that. From what I can tell, `net.minecraft.world.level.block.state.BlockBehaviour.getseed()` should only be called once when the block is loaded in, not multiple times, and definitely not at that speed.

**Comment by rfresh2** [comment]
it actually is called very frequently

you can see the artifacts on the interaction boxes of blocks like flowers if you hover over them

as for why those chunks specifically, its most likely due to block, light, or chunk updates the server is sending you causing a chunk mesh rebuild

**Comment by Kladki** [comment]
Ah ok, thanks for the explanation. Also, I wonder if storing a random offset for each chunk, and dropping them when the chunk is unloaded or the player leaves the server/world would be a good method to still have rotations, while avoiding visual issues like this.

**Comment by rfresh2** [comment]
sounds possible but more complex to manage. but if you're interested you I do accept PR's :)

**Comment by Kladki** [comment]
Ok, I might give it a go. BTW, where can I find the javadocs for modules like `net.minecraft.core` and `net.minecraft.world.level.block.state`? They don't seem to be on the yarn javadoc.

**Comment by rfresh2** [comment]
this mod uses mojang mappings, not yarn mappings

if you are expecting javadocs for internal mc classes you're not going to find any for any kind of mappings though.

you need to look at the decompiled mc source code. e.g. https://github.com/NikitaCartes-archive/MinecraftDeobfuscated-Mojang
